apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: kafka-transforms
    meta.helm.sh/release-namespace: kafka-transforms 
  name: kafka-transforms
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp-3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: kafka-transforms
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
